name: aws_encryption_sdk
description: >
  An implementation of the AWS Encryption SDK in Dart.
  Encrypt and decrypt data using AWS KMS, AES and RSA keys.
  Interoperates with the Java, C and Python implementations.

version: 1.0.0
repository: https://github.com/richardheap/aws_encryption_sdk

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  aws_kms_api: ^2.0.0
  ffi: ^2.0.2
  pointycastle: ^3.7.3

dev_dependencies:
  basic_utils: ^4.5.2
  lints: ^2.1.1
  test: ^1.20.1

false_secrets:
  - /test/keyring/rsa_keyring_test.dart