name: aws_encryption_sdk
description: An implementation of the AWS Encryption SDK in Dart
version: 0.1.0
repository: https://github.com/richardheap/aws_encryption_sdk

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  aws_kms_api: ^1.2.0
  ffi: ^1.1.2
  pointycastle: ^3.5.1

dev_dependencies:
  basic_utils: ^4.2.0
  lints: ^1.0.1
  test: ^1.20.1

false_secrets:
  - /test/keyring/rsa_keyring_test.dart